const faDefinitions = {
    "Common": {
        "far-smile": "Emoji",
        "thumbs-up": "Hands",
        "thumbs-down": "Hands",
        "heart": "Health",
        "flask": "Objects",
        "rocket": "Objects",
        "dollar-sign": "Currency",
        "shopping-cart": "Payments & Shopping",
        "shipping-fast": "Logistics",
        "database": "Computers",
        "mobile-alt": "Computers",
        "laptop": "Computers",
        "desktop": "Computers",
        "file": "Files",
        "far-calendar-alt": "Date & Time",
        "far-clock": "Date & Time",
        "check": "Interfaces",
        "exclamation-triangle": "Interfaces",
        "flag-checkered": "Interfaces",
        "user": "Interfaces",
        "far-envelope": "Business",
        "far-comment-alt": "Chat",
        "far-bell": "Maps",
        "key": "Maps",
        "map-marker-alt": "Maps"
    },
    "Accessibility": {
        "american-sign-language-interpreting": "American Sign Language Interpreting",
        "assistive-listening-systems": "Assistive Listening Systems",
        "audio-description": "Audio Description",
        "blind": "Blind",
        "braille": "Braille",
        "closed-captioning": "Closed Captioning",
        "far-closed-captioning": "Closed Captioning",
        "deaf": "Deaf",
        "low-vision": "Low Vision",
        "phone-volume": "Phone Volume",
        "question-circle": "Question Circle",
        "far-question-circle": "Question Circle",
        "sign-language": "Sign Language",
        "tty": "Tty",
        "universal-access": "Universal Access",
        "wheelchair": "Wheelchair"
    },
    "Animals": {
        "cat": "Cat",
        "crow": "Crow",
        "dog": "Dog",
        "dove": "Dove",
        "dragon": "Dragon",
        "feather": "Feather",
        "feather-alt": "Feather Alt",
        "fish": "Fish",
        "frog": "Frog",
        "hippo": "Hippo",
        "horse": "Horse",
        "horse-head": "Horse Head",
        "kiwi-bird": "Kiwi Bird",
        "otter": "Otter",
        "paw": "Paw",
        "spider": "Spider"
    },
    "Arrows": {
        "angle-double-down": "Angle Double Down",
        "angle-double-left": "Angle Double Left",
        "angle-double-right": "Angle Double Right",
        "angle-double-up": "Angle Double Up",
        "angle-down": "Angle Down",
        "angle-left": "Angle Left",
        "angle-right": "Angle Right",
        "angle-up": "Angle Up",
        "arrow-alt-circle-down": "Arrow Alt Circle Down",
        "far-arrow-alt-circle-down": "Arrow Alt Circle Down",
        "arrow-alt-circle-left": "Arrow Alt Circle Left",
        "far-arrow-alt-circle-left": "Arrow Alt Circle Left",
        "arrow-alt-circle-right": "Arrow Alt Circle Right",
        "far-arrow-alt-circle-right": "Arrow Alt Circle Right",
        "arrow-alt-circle-up": "Arrow Alt Circle Up",
        "far-arrow-alt-circle-up": "Arrow Alt Circle Up",
        "arrow-circle-down": "Arrow Circle Down",
        "arrow-circle-left": "Arrow Circle Left",
        "arrow-circle-right": "Arrow Circle Right",
        "arrow-circle-up": "Arrow Circle Up",
        "arrow-down": "Arrow Down",
        "arrow-left": "Arrow Left",
        "arrow-right": "Arrow Right",
        "arrow-up": "Arrow Up",
        "arrows-alt": "Arrows Alt",
        "arrows-alt-h": "Arrows Alt H",
        "arrows-alt-v": "Arrows Alt V",
        "caret-down": "Caret Down",
        "caret-left": "Caret Left",
        "caret-right": "Caret Right",
        "caret-square-down": "Caret Square Down",
        "far-caret-square-down": "Caret Square Down",
        "caret-square-left": "Caret Square Left",
        "far-caret-square-left": "Caret Square Left",
        "caret-square-right": "Caret Square Right",
        "far-caret-square-right": "Caret Square Right",
        "caret-square-up": "Caret Square Up",
        "far-caret-square-up": "Caret Square Up",
        "caret-up": "Caret Up",
        "cart-arrow-down": "Cart Arrow Down",
        "chart-line": "Chart Line",
        "chevron-circle-down": "Chevron Circle Down",
        "chevron-circle-left": "Chevron Circle Left",
        "chevron-circle-right": "Chevron Circle Right",
        "chevron-circle-up": "Chevron Circle Up",
        "chevron-down": "Chevron Down",
        "chevron-left": "Chevron Left",
        "chevron-right": "Chevron Right",
        "chevron-up": "Chevron Up",
        "cloud-download-alt": "Cloud Download Alt",
        "cloud-upload-alt": "Cloud Upload Alt",
        "compress-arrows-alt": "Compress Arrows Alt",
        "download": "Download",
        "exchange-alt": "Exchange Alt",
        "expand-arrows-alt": "Expand Arrows Alt",
        "external-link-alt": "External Link Alt",
        "external-link-square-alt": "External Link Square Alt",
        "hand-point-down": "Hand Point Down",
        "far-hand-point-down": "Hand Point Down",
        "hand-point-left": "Hand Point Left",
        "far-hand-point-left": "Hand Point Left",
        "hand-point-right": "Hand Point Right",
        "far-hand-point-right": "Hand Point Right",
        "hand-point-up": "Hand Point Up",
        "far-hand-point-up": "Hand Point Up",
        "hand-pointer": "Hand Pointer",
        "far-hand-pointer": "Hand Pointer",
        "history": "History",
        "level-down-alt": "Level Down Alt",
        "level-up-alt": "Level Up Alt",
        "location-arrow": "Location Arrow",
        "long-arrow-alt-down": "Long Arrow Alt Down",
        "long-arrow-alt-left": "Long Arrow Alt Left",
        "long-arrow-alt-right": "Long Arrow Alt Right",
        "long-arrow-alt-up": "Long Arrow Alt Up",
        "mouse-pointer": "Mouse Pointer",
        "play": "Play",
        "random": "Random",
        "recycle": "Recycle",
        "redo": "Redo",
        "redo-alt": "Redo Alt",
        "reply": "Reply",
        "reply-all": "Reply All",
        "retweet": "Retweet",
        "share": "Share",
        "share-square": "Share Square",
        "far-share-square": "Share Square",
        "sign-in-alt": "Sign In Alt",
        "sign-out-alt": "Sign Out Alt",
        "sort": "Sort",
        "sort-alpha-down": "Sort Alpha Down",
        "sort-alpha-up": "Sort Alpha Up",
        "sort-amount-down": "Sort Amount Down",
        "sort-amount-up": "Sort Amount Up",
        "sort-down": "Sort Down",
        "sort-numeric-down": "Sort Numeric Down",
        "sort-numeric-up": "Sort Numeric Up",
        "sort-up": "Sort Up",
        "sync": "Sync",
        "sync-alt": "Sync Alt",
        "text-height": "Text Height",
        "text-width": "Text Width",
        "undo": "Undo",
        "undo-alt": "Undo Alt",
        "upload": "Upload"
    },
    "Audio & Video": {
        "audio-description": "Audio Description",
        "backward": "Backward",
        "broadcast-tower": "Broadcast Tower",
        "circle": "Circle",
        "far-circle": "Circle",
        "closed-captioning": "Closed Captioning",
        "far-closed-captioning": "Closed Captioning",
        "compress": "Compress",
        "compress-arrows-alt": "Compress Arrows Alt",
        "eject": "Eject",
        "expand": "Expand",
        "expand-arrows-alt": "Expand Arrows Alt",
        "fast-backward": "Fast Backward",
        "fast-forward": "Fast Forward",
        "file-audio": "File Audio",
        "far-file-audio": "File Audio",
        "file-video": "File Video",
        "far-file-video": "File Video",
        "film": "Film",
        "forward": "Forward",
        "headphones": "Headphones",
        "microphone": "Microphone",
        "microphone-alt": "Microphone Alt",
        "microphone-alt-slash": "Microphone Alt Slash",
        "microphone-slash": "Microphone Slash",
        "music": "Music",
        "pause": "Pause",
        "pause-circle": "Pause Circle",
        "far-pause-circle": "Pause Circle",
        "phone-volume": "Phone Volume",
        "play": "Play",
        "play-circle": "Play Circle",
        "far-play-circle": "Play Circle",
        "podcast": "Podcast",
        "random": "Random",
        "redo": "Redo",
        "redo-alt": "Redo Alt",
        "rss": "Rss",
        "rss-square": "Rss Square",
        "step-backward": "Step Backward",
        "step-forward": "Step Forward",
        "stop": "Stop",
        "stop-circle": "Stop Circle",
        "far-stop-circle": "Stop Circle",
        "sync": "Sync",
        "sync-alt": "Sync Alt",
        "undo": "Undo",
        "undo-alt": "Undo Alt",
        "video": "Video",
        "volume-down": "Volume Down",
        "volume-mute": "Volume Mute",
        "volume-off": "Volume Off",
        "volume-up": "Volume Up"
    },
    "Automotive": {
        "air-freshener": "Air Freshener",
        "ambulance": "Ambulance",
        "bus": "Bus",
        "bus-alt": "Bus Alt",
        "car": "Car",
        "car-alt": "Car Alt",
        "car-battery": "Car Battery",
        "car-crash": "Car Crash",
        "car-side": "Car Side",
        "charging-station": "Charging Station",
        "gas-pump": "Gas Pump",
        "motorcycle": "Motorcycle",
        "oil-can": "Oil Can",
        "shuttle-van": "Shuttle Van",
        "tachometer-alt": "Tachometer Alt",
        "taxi": "Taxi",
        "truck": "Truck",
        "truck-monster": "Truck Monster",
        "truck-pickup": "Truck Pickup"
    },
    "Autumn": {
        "apple-alt": "Apple Alt",
        "campground": "Campground",
        "cloud-sun": "Cloud Sun",
        "drumstick-bite": "Drumstick Bite",
        "football-ball": "Football Ball",
        "hiking": "Hiking",
        "mountain": "Mountain",
        "tractor": "Tractor",
        "tree": "Tree",
        "wind": "Wind",
        "wine-bottle": "Wine Bottle"
    },
    "brands": {
        "magento": "Magento",
        "forumbee": "Forumbee",
        "viadeo-square": "Viadeo Square",
        "medrt": "Medrt",
        "lyft": "Lyft",
        "joomla": "Joomla",
        "bitbucket": "Bitbucket",
        "alipay": "Alipay",
        "hotjar": "Hotjar",
        "hornbill": "Hornbill",
        "gitkraken": "Gitkraken",
        "etsy": "Etsy",
        "readme": "Readme",
        "tumblr-square": "Tumblr Square",
        "git-square": "Git Square",
        "wordpress": "Wordpress",
        "creative-commons-sampling-plus": "Creative Commons Sampling Plus",
        "studiovinari": "Studiovinari",
        "pinterest-p": "Pinterest P",
        "earlybirds": "Earlybirds",
        "docker": "Docker",
        "pagelines": "Pagelines",
        "itunes-note": "Itunes Note",
        "kaggle": "Kaggle",
        "steam-symbol": "Steam Symbol",
        "viber": "Viber",
        "cpanel": "Cpanel",
        "strava": "Strava",
        "yarn": "Yarn",
        "uikit": "Uikit",
        "pinterest": "Pinterest",
        "ns8": "Ns8",
        "houzz": "Houzz",
        "sistrix": "Sistrix",
        "bandcamp": "Bandcamp",
        "adversal": "Adversal",
        "creative-commons-nc-eu": "Creative Commons Nc Eu",
        "xbox": "Xbox",
        "speakap": "Speakap",
        "bity": "Bity",
        "acquisitions-incorporated": "Acquisitions Incorporated",
        "replyd": "Replyd",
        "android": "Android",
        "yandex": "Yandex",
        "medapps": "Medapps",
        "cuttlefish": "Cuttlefish",
        "themeco": "Themeco",
        "vine": "Vine",
        "viadeo": "Viadeo",
        "flipboard": "Flipboard",
        "slack-hash": "Slack Hash",
        "ioxhost": "Ioxhost",
        "optin-monster": "Optin Monster",
        "megaport": "Megaport",
        "font-awesome-flag": "Font Awesome Flag",
        "drupal": "Drupal",
        "facebook-square": "Facebook Square",
        "connectdevelop": "Connectdevelop",
        "twitch": "Twitch",
        "patreon": "Patreon",
        "wpressr": "Wpressr",
        "free-code-camp": "Free Code Camp",
        "stack-overflow": "Stack Overflow",
        "creative-commons-pd-alt": "Creative Commons Pd Alt",
        "shopware": "Shopware",
        "snapchat-ghost": "Snapchat Ghost",
        "think-peaks": "Think Peaks",
        "researchgate": "Researchgate",
        "hips": "Hips",
        "behance-square": "Behance Square",
        "vimeo-square": "Vimeo Square",
        "fonticons": "Fonticons",
        "y-combinator": "Y Combinator",
        "app-store-ios": "App Store Ios",
        "jenkins": "Jenkins",
        "galactic-republic": "Galactic Republic",
        "creative-commons-remix": "Creative Commons Remix",
        "rockrms": "Rockrms",
        "node-js": "Node Js",
        "gratipay": "Gratipay",
        "pushed": "Pushed",
        "fly": "Fly",
        "spotify": "Spotify",
        "product-hunt": "Product Hunt",
        "scribd": "Scribd",
        "renren": "Renren",
        "skyatlas": "Skyatlas",
        "meetup": "Meetup",
        "snapchat-square": "Snapchat Square",
        "yelp": "Yelp",
        "delicious": "Delicious",
        "google-plus-g": "Google Plus G",
        "keybase": "Keybase",
        "viacoin": "Viacoin",
        "xing-square": "Xing Square",
        "chrome": "Chrome",
        "critical-role": "Critical Role",
        "jedi-order": "Jedi Order",
        "cc-discover": "Cc Discover",
        "pied-piper-pp": "Pied Piper Pp",
        "neos": "Neos",
        "blogger-b": "Blogger B",
        "ravelry": "Ravelry",
        "usps": "Usps",
        "accessible-icon": "Accessible Icon",
        "freebsd": "Freebsd",
        "css3-alt": "Css3 Alt",
        "facebook-f": "Facebook F",
        "centos": "Centos",
        "amazon": "Amazon",
        "fonticons-fi": "Fonticons Fi",
        "dashcube": "Dashcube",
        "cc-apple-pay": "Cc Apple Pay",
        "vnv": "Vnv",
        "wix": "Wix",
        "font-awesome": "Font Awesome",
        "python": "Python",
        "ubuntu": "Ubuntu",
        "weebly": "Weebly",
        "wpforms": "Wpforms",
        "dhl": "Dhl",
        "get-pocket": "Get Pocket",
        "whmcs": "Whmcs",
        "staylinked": "Staylinked",
        "bluetooth": "Bluetooth",
        "modx": "Modx",
        "bimobject": "Bimobject",
        "glide-g": "Glide G",
        "windows": "Windows",
        "sith": "Sith",
        "keycdn": "Keycdn",
        "redhat": "Redhat",
        "servicestack": "Servicestack",
        "the-red-yeti": "The Red Yeti",
        "uber": "Uber",
        "lastfm": "Lastfm",
        "cc-amex": "Cc Amex",
        "creative-commons-sampling": "Creative Commons Sampling",
        "zhihu": "Zhihu",
        "d-and-d-beyond": "D And D Beyond",
        "playstation": "Playstation",
        "dribbble": "Dribbble",
        "telegram-plane": "Telegram Plane",
        "diaspora": "Diaspora",
        "deskpro": "Deskpro",
        "accusoft": "Accusoft",
        "codiepie": "Codiepie",
        "stripe": "Stripe",
        "fort-awesome-alt": "Fort Awesome Alt",
        "canadian-maple-leaf": "Canadian Maple Leaf",
        "suse": "Suse",
        "periscope": "Periscope",
        "stack-exchange": "Stack Exchange",
        "behance": "Behance",
        "imdb": "Imdb",
        "app-store": "App Store",
        "palfed": "Palfed",
        "envira": "Envira",
        "weibo": "Weibo",
        "hacker-news": "Hacker News",
        "mixcloud": "Mixcloud",
        "tumblr": "Tumblr",
        "apple-pay": "Apple Pay",
        "steam-square": "Steam Square",
        "microsoft": "Microsoft",
        "phoenix-squadron": "Phoenix Squadron",
        "line": "Line",
        "reddit": "Reddit",
        "yoast": "Yoast",
        "rev": "Rev",
        "codepen": "Codepen",
        "sellsy": "Sellsy",
        "goodreads": "Goodreads",
        "mix": "Mix",
        "tripadvisor": "Tripadvisor",
        "themeisle": "Themeisle",
        "dyalog": "Dyalog",
        "google": "Google",
        "stumbleupon": "Stumbleupon",
        "pied-piper-hat": "Pied Piper Hat",
        "hubspot": "Hubspot",
        "quora": "Quora",
        "php": "Php",
        "squarespace": "Squarespace",
        "medium-m": "Medium M",
        "telegram": "Telegram",
        "google-plus-square": "Google Plus Square",
        "gripfire": "Gripfire",
        "hooli": "Hooli",
        "html5": "Html5",
        "draft2digital": "Draft2digital",
        "cc-amazon-pay": "Cc Amazon Pay",
        "gg-circle": "Gg Circle",
        "glide": "Glide",
        "google-drive": "Google Drive",
        "affiliatetheme": "Affiliatetheme",
        "centercode": "Centercode",
        "hire-a-helper": "Hire A Helper",
        "weixin": "Weixin",
        "ups": "Ups",
        "teamspeak": "Teamspeak",
        "gitter": "Gitter",
        "whatsapp": "Whatsapp",
        "old-republic": "Old Republic",
        "reddit-alien": "Reddit Alien",
        "facebook-messenger": "Facebook Messenger",
        "tencent-weibo": "Tencent Weibo",
        "odnoklassniki": "Odnoklassniki",
        "typo3": "Typo3",
        "red-river": "Red River",
        "erlang": "Erlang",
        "deploydog": "Deploydog",
        "node": "Node",
        "creative-commons-sa": "Creative Commons Sa",
        "yandex-international": "Yandex International",
        "wikipedia-w": "Wikipedia W",
        "schlix": "Schlix",
        "cc-stripe": "Cc Stripe",
        "dev": "Dev",
        "digg": "Digg",
        "audible": "Audible",
        "bluetooth-b": "Bluetooth B",
        "lastfm-square": "Lastfm Square",
        "amazon-pay": "Amazon Pay",
        "mailchimp": "Mailchimp",
        "reddit-square": "Reddit Square",
        "supple": "Supple",
        "mastodon": "Mastodon",
        "hacker-news-square": "Hacker News Square",
        "react": "React",
        "soundcloud": "Soundcloud",
        "figma": "Figma",
        "wpexplorer": "Wpexplorer",
        "creative-commons-nc-jp": "Creative Commons Nc Jp",
        "gitlab": "Gitlab",
        "nintendo-switch": "Nintendo Switch",
        "untappd": "Untappd",
        "safari": "Safari",
        "nimblr": "Nimblr",
        "less": "Less",
        "opencart": "Opencart",
        "hackerrank": "Hackerrank",
        "uniregistry": "Uniregistry",
        "cloudsmith": "Cloudsmith",
        "youtube": "Youtube",
        "flickr": "Flickr",
        "linode": "Linode",
        "500px": "500px",
        "fantasy-flight-games": "Fantasy Flight Games",
        "gulp": "Gulp",
        "twitter": "Twitter",
        "discord": "Discord",
        "jsfiddle": "Jsfiddle",
        "black-tie": "Black Tie",
        "digital-ocean": "Digital Ocean",
        "sourcetree": "Sourcetree",
        "d-and-d": "D And D",
        "xing": "Xing",
        "autoprefixer": "Autoprefixer",
        "algolia": "Algolia",
        "angrycreative": "Angrycreative",
        "vk": "Vk",
        "foursquare": "Foursquare",
        "leanpub": "Leanpub",
        "java": "Java",
        "dribbble-square": "Dribbble Square",
        "apple": "Apple",
        "mizuni": "Mizuni",
        "rebel": "Rebel",
        "github-alt": "Github Alt",
        "rocketchat": "Rocketchat",
        "grav": "Grav",
        "pinterest-square": "Pinterest Square",
        "sketch": "Sketch",
        "medium": "Medium",
        "vuejs": "Vuejs",
        "mandalorian": "Mandalorian",
        "adobe": "Adobe",
        "qq": "Qq",
        "reacteurope": "Reacteurope",
        "cloudversify": "Cloudversify",
        "cloudscale": "Cloudscale",
        "pied-piper-alt": "Pied Piper Alt",
        "kickstarter": "Kickstarter",
        "asymmetrik": "Asymmetrik",
        "js-square": "Js Square",
        "ember": "Ember",
        "empire": "Empire",
        "creative-commons-nd": "Creative Commons Nd",
        "instagram": "Instagram",
        "superpowers": "Superpowers",
        "usb": "Usb",
        "aws": "Aws",
        "sticker-mule": "Sticker Mule",
        "mendeley": "Mendeley",
        "page4": "Page4",
        "font-awesome-alt": "Font Awesome Alt",
        "whatsapp-square": "Whatsapp Square",
        "quinscape": "Quinscape",
        "creative-commons-pd": "Creative Commons Pd",
        "osi": "Osi",
        "openid": "Openid",
        "snapchat": "Snapchat",
        "stripe-s": "Stripe S",
        "stumbleupon-circle": "Stumbleupon Circle",
        "edge": "Edge",
        "simplybuilt": "Simplybuilt",
        "js": "Js",
        "adn": "Adn",
        "odnoklassniki-square": "Odnoklassniki Square",
        "internet-explorer": "Internet Explorer",
        "gg": "Gg",
        "itunes": "Itunes",
        "fort-awesome": "Fort Awesome",
        "jira": "Jira",
        "creative-commons-by": "Creative Commons By",
        "r-project": "R Project",
        "cc-paypal": "Cc Paypal",
        "ebay": "Ebay",
        "penny-arcade": "Penny Arcade",
        "avianex": "Avianex",
        "github": "Github",
        "wpbeginner": "Wpbeginner",
        "angular": "Angular",
        "amilia": "Amilia",
        "joget": "Joget",
        "phabricator": "Phabricator",
        "paypal": "Paypal",
        "steam": "Steam",
        "laravel": "Laravel",
        "ello": "Ello",
        "kickstarter-k": "Kickstarter K",
        "blackberry": "Blackberry",
        "discourse": "Discourse",
        "cc-mastercard": "Cc Mastercard",
        "slack": "Slack",
        "artstation": "Artstation",
        "wolf-pack-battalion": "Wolf Pack Battalion",
        "css3": "Css3",
        "apper": "Apper",
        "fedora": "Fedora",
        "yahoo": "Yahoo",
        "markdown": "Markdown",
        "dochub": "Dochub",
        "expeditedssl": "Expeditedssl",
        "napster": "Napster",
        "creative-commons-nc": "Creative Commons Nc",
        "creative-commons": "Creative Commons",
        "aviato": "Aviato",
        "cc-visa": "Cc Visa",
        "vimeo": "Vimeo",
        "ethereum": "Ethereum",
        "angellist": "Angellist",
        "maxcdn": "Maxcdn",
        "contao": "Contao",
        "shirtsinbulk": "Shirtsinbulk",
        "font-awesome-logo-full": "Font Awesome Logo Full",
        "grunt": "Grunt",
        "cc-diners-club": "Cc Diners Club",
        "confluence": "Confluence",
        "linkedin": "Linkedin",
        "twitter-square": "Twitter Square",
        "gofore": "Gofore",
        "firefox": "Firefox",
        "nutritionix": "Nutritionix",
        "cc-jcb": "Cc Jcb",
        "google-wallet": "Google Wallet",
        "git": "Git",
        "resolving": "Resolving",
        "atlassian": "Atlassian",
        "creative-commons-share": "Creative Commons Share",
        "first-order": "First Order",
        "searchengin": "Searchengin",
        "fulcrum": "Fulcrum",
        "linkedin-in": "Linkedin In",
        "buysellads": "Buysellads",
        "ussunnah": "Ussunnah",
        "korvue": "Korvue",
        "github-square": "Github Square",
        "intercom": "Intercom",
        "dropbox": "Dropbox",
        "vaadin": "Vaadin",
        "deviantart": "Deviantart",
        "trello": "Trello",
        "first-order-alt": "First Order Alt",
        "creative-commons-zero": "Creative Commons Zero",
        "youtube-square": "Youtube Square",
        "btc": "Btc",
        "wordpress-simple": "Wordpress Simple",
        "bitcoin": "Bitcoin",
        "google-play": "Google Play",
        "fedex": "Fedex",
        "galactic-senate": "Galactic Senate",
        "invision": "Invision",
        "skype": "Skype",
        "phoenix-framework": "Phoenix Framework",
        "opera": "Opera",
        "npm": "Npm",
        "raspberry-pi": "Raspberry Pi",
        "wizards-of-the-coast": "Wizards Of The Coast",
        "sellcast": "Sellcast",
        "slideshare": "Slideshare",
        "google-plus": "Google Plus",
        "linux": "Linux",
        "blogger": "Blogger",
        "vimeo-v": "Vimeo V",
        "elementor": "Elementor",
        "monero": "Monero",
        "pied-piper": "Pied Piper",
        "sass": "Sass",
        "trade-federation": "Trade Federation",
        "firstdraft": "Firstdraft",
        "buromobelexperte": "Buromobelexperte",
        "goodreads-g": "Goodreads G",
        "facebook": "Facebook"
    },
    "Buildings": {
        "building": "Building",
        "far-building": "Building",
        "campground": "Campground",
        "church": "Church",
        "city": "City",
        "dungeon": "Dungeon",
        "gopuram": "Gopuram",
        "home": "Home",
        "hospital": "Hospital",
        "far-hospital": "Hospital",
        "hospital-alt": "Hospital Alt",
        "hotel": "Hotel",
        "house-damage": "House Damage",
        "igloo": "Igloo",
        "industry": "Industry",
        "landmark": "Landmark",
        "mosque": "Mosque",
        "place-of-worship": "Place Of Worship",
        "school": "School",
        "synagogue": "Synagogue",
        "torii-gate": "Torii Gate",
        "university": "University",
        "vihara": "Vihara",
        "warehouse": "Warehouse"
    },
    "Business": {
        "address-book": "Address Book",
        "far-address-book": "Address Book",
        "address-card": "Address Card",
        "far-address-card": "Address Card",
        "archive": "Archive",
        "balance-scale": "Balance Scale",
        "birthday-cake": "Birthday Cake",
        "book": "Book",
        "briefcase": "Briefcase",
        "building": "Building",
        "far-building": "Building",
        "bullhorn": "Bullhorn",
        "bullseye": "Bullseye",
        "business-time": "Business Time",
        "calculator": "Calculator",
        "calendar": "Calendar",
        "far-calendar": "Calendar",
        "calendar-alt": "Calendar Alt",
        "far-calendar-alt": "Calendar Alt",
        "certificate": "Certificate",
        "chart-area": "Chart Area",
        "chart-bar": "Chart Bar",
        "far-chart-bar": "Chart Bar",
        "chart-line": "Chart Line",
        "chart-pie": "Chart Pie",
        "city": "City",
        "clipboard": "Clipboard",
        "far-clipboard": "Clipboard",
        "coffee": "Coffee",
        "columns": "Columns",
        "compass": "Compass",
        "far-compass": "Compass",
        "copy": "Copy",
        "far-copy": "Copy",
        "copyright": "Copyright",
        "far-copyright": "Copyright",
        "cut": "Cut",
        "edit": "Edit",
        "far-edit": "Edit",
        "envelope": "Envelope",
        "far-envelope": "Envelope",
        "envelope-open": "Envelope Open",
        "far-envelope-open": "Envelope Open",
        "envelope-square": "Envelope Square",
        "eraser": "Eraser",
        "fax": "Fax",
        "file": "File",
        "far-file": "File",
        "file-alt": "File Alt",
        "far-file-alt": "File Alt",
        "folder": "Folder",
        "far-folder": "Folder",
        "folder-minus": "Folder Minus",
        "folder-open": "Folder Open",
        "far-folder-open": "Folder Open",
        "folder-plus": "Folder Plus",
        "glasses": "Glasses",
        "globe": "Globe",
        "highlighter": "Highlighter",
        "industry": "Industry",
        "landmark": "Landmark",
        "marker": "Marker",
        "paperclip": "Paperclip",
        "paste": "Paste",
        "pen": "Pen",
        "pen-alt": "Pen Alt",
        "pen-fancy": "Pen Fancy",
        "pen-nib": "Pen Nib",
        "pen-square": "Pen Square",
        "pencil-alt": "Pencil Alt",
        "percent": "Percent",
        "phone": "Phone",
        "phone-slash": "Phone Slash",
        "phone-square": "Phone Square",
        "phone-volume": "Phone Volume",
        "print": "Print",
        "project-diagram": "Project Diagram",
        "registered": "Registered",
        "far-registered": "Registered",
        "save": "Save",
        "far-save": "Save",
        "sitemap": "Sitemap",
        "socks": "Socks",
        "sticky-note": "Sticky Note",
        "far-sticky-note": "Sticky Note",
        "stream": "Stream",
        "table": "Table",
        "tag": "Tag",
        "tags": "Tags",
        "tasks": "Tasks",
        "thumbtack": "Thumbtack",
        "trademark": "Trademark",
        "wallet": "Wallet"
    },
    "Charity": {
        "dollar-sign": "Dollar Sign",
        "donate": "Donate",
        "dove": "Dove",
        "gift": "Gift",
        "globe": "Globe",
        "hand-holding-heart": "Hand Holding Heart",
        "hand-holding-usd": "Hand Holding Usd",
        "hands-helping": "Hands Helping",
        "handshake": "Handshake",
        "far-handshake": "Handshake",
        "heart": "Heart",
        "far-heart": "Heart",
        "leaf": "Leaf",
        "parachute-box": "Parachute Box",
        "piggy-bank": "Piggy Bank",
        "ribbon": "Ribbon",
        "seedling": "Seedling"
    },
    "Chat": {
        "comment": "Comment",
        "far-comment": "Comment",
        "comment-alt": "Comment Alt",
        "far-comment-alt": "Comment Alt",
        "comment-dots": "Comment Dots",
        "far-comment-dots": "Comment Dots",
        "comment-medical": "Comment Medical",
        "comment-slash": "Comment Slash",
        "comments": "Comments",
        "far-comments": "Comments",
        "frown": "Frown",
        "far-frown": "Frown",
        "meh": "Meh",
        "far-meh": "Meh",
        "phone": "Phone",
        "phone-slash": "Phone Slash",
        "poo": "Poo",
        "quote-left": "Quote Left",
        "quote-right": "Quote Right",
        "smile": "Smile",
        "far-smile": "Smile",
        "sms": "Sms",
        "video": "Video",
        "video-slash": "Video Slash"
    },
    "Chess": {
        "chess": "Chess",
        "chess-bishop": "Chess Bishop",
        "chess-board": "Chess Board",
        "chess-king": "Chess King",
        "chess-knight": "Chess Knight",
        "chess-pawn": "Chess Pawn",
        "chess-queen": "Chess Queen",
        "chess-rook": "Chess Rook",
        "square-full": "Square Full"
    },
    "Code": {
        "archive": "Archive",
        "barcode": "Barcode",
        "bath": "Bath",
        "bug": "Bug",
        "code": "Code",
        "code-branch": "Code Branch",
        "coffee": "Coffee",
        "file": "File",
        "far-file": "File",
        "file-alt": "File Alt",
        "far-file-alt": "File Alt",
        "file-code": "File Code",
        "far-file-code": "File Code",
        "filter": "Filter",
        "fire-extinguisher": "Fire Extinguisher",
        "folder": "Folder",
        "far-folder": "Folder",
        "folder-open": "Folder Open",
        "far-folder-open": "Folder Open",
        "keyboard": "Keyboard",
        "far-keyboard": "Keyboard",
        "microchip": "Microchip",
        "project-diagram": "Project Diagram",
        "qrcode": "Qrcode",
        "shield-alt": "Shield Alt",
        "sitemap": "Sitemap",
        "stream": "Stream",
        "terminal": "Terminal",
        "user-secret": "User Secret",
        "window-close": "Window Close",
        "far-window-close": "Window Close",
        "window-maximize": "Window Maximize",
        "far-window-maximize": "Window Maximize",
        "window-minimize": "Window Minimize",
        "far-window-minimize": "Window Minimize",
        "window-restore": "Window Restore",
        "far-window-restore": "Window Restore"
    },
    "Communication": {
        "address-book": "Address Book",
        "far-address-book": "Address Book",
        "address-card": "Address Card",
        "far-address-card": "Address Card",
        "american-sign-language-interpreting": "American Sign Language Interpreting",
        "assistive-listening-systems": "Assistive Listening Systems",
        "at": "At",
        "bell": "Bell",
        "far-bell": "Bell",
        "bell-slash": "Bell Slash",
        "far-bell-slash": "Bell Slash",
        "broadcast-tower": "Broadcast Tower",
        "bullhorn": "Bullhorn",
        "chalkboard": "Chalkboard",
        "comment": "Comment",
        "far-comment": "Comment",
        "comment-alt": "Comment Alt",
        "far-comment-alt": "Comment Alt",
        "comments": "Comments",
        "far-comments": "Comments",
        "envelope": "Envelope",
        "far-envelope": "Envelope",
        "envelope-open": "Envelope Open",
        "far-envelope-open": "Envelope Open",
        "envelope-square": "Envelope Square",
        "fax": "Fax",
        "inbox": "Inbox",
        "language": "Language",
        "microphone": "Microphone",
        "microphone-alt": "Microphone Alt",
        "microphone-alt-slash": "Microphone Alt Slash",
        "microphone-slash": "Microphone Slash",
        "mobile": "Mobile",
        "mobile-alt": "Mobile Alt",
        "paper-plane": "Paper Plane",
        "far-paper-plane": "Paper Plane",
        "phone": "Phone",
        "phone-slash": "Phone Slash",
        "phone-square": "Phone Square",
        "phone-volume": "Phone Volume",
        "rss": "Rss",
        "rss-square": "Rss Square",
        "tty": "Tty",
        "wifi": "Wifi"
    },
    "Computers": {
        "database": "Database",
        "desktop": "Desktop",
        "download": "Download",
        "ethernet": "Ethernet",
        "hdd": "Hdd",
        "far-hdd": "Hdd",
        "headphones": "Headphones",
        "keyboard": "Keyboard",
        "far-keyboard": "Keyboard",
        "laptop": "Laptop",
        "memory": "Memory",
        "microchip": "Microchip",
        "mobile": "Mobile",
        "mobile-alt": "Mobile Alt",
        "plug": "Plug",
        "power-off": "Power Off",
        "print": "Print",
        "satellite": "Satellite",
        "satellite-dish": "Satellite Dish",
        "save": "Save",
        "far-save": "Save",
        "sd-card": "Sd Card",
        "server": "Server",
        "sim-card": "Sim Card",
        "stream": "Stream",
        "tablet": "Tablet",
        "tablet-alt": "Tablet Alt",
        "tv": "Tv",
        "upload": "Upload"
    },
    "Currency": {
        "dollar-sign": "Dollar Sign",
        "euro-sign": "Euro Sign",
        "hryvnia": "Hryvnia",
        "lira-sign": "Lira Sign",
        "money-bill": "Money Bill",
        "money-bill-alt": "Money Bill Alt",
        "far-money-bill-alt": "Money Bill Alt",
        "money-bill-wave": "Money Bill Wave",
        "money-bill-wave-alt": "Money Bill Wave Alt",
        "money-check": "Money Check",
        "money-check-alt": "Money Check Alt",
        "pound-sign": "Pound Sign",
        "ruble-sign": "Ruble Sign",
        "rupee-sign": "Rupee Sign",
        "shekel-sign": "Shekel Sign",
        "tenge": "Tenge",
        "won-sign": "Won Sign",
        "yen-sign": "Yen Sign"
    },
    "Date & Time": {
        "bell": "Bell",
        "far-bell": "Bell",
        "bell-slash": "Bell Slash",
        "far-bell-slash": "Bell Slash",
        "calendar": "Calendar",
        "far-calendar": "Calendar",
        "calendar-alt": "Calendar Alt",
        "far-calendar-alt": "Calendar Alt",
        "calendar-check": "Calendar Check",
        "far-calendar-check": "Calendar Check",
        "calendar-minus": "Calendar Minus",
        "far-calendar-minus": "Calendar Minus",
        "calendar-plus": "Calendar Plus",
        "far-calendar-plus": "Calendar Plus",
        "calendar-times": "Calendar Times",
        "far-calendar-times": "Calendar Times",
        "clock": "Clock",
        "far-clock": "Clock",
        "hourglass": "Hourglass",
        "far-hourglass": "Hourglass",
        "hourglass-end": "Hourglass End",
        "hourglass-half": "Hourglass Half",
        "hourglass-start": "Hourglass Start",
        "stopwatch": "Stopwatch"
    },
    "Design": {
        "adjust": "Adjust",
        "bezier-curve": "Bezier Curve",
        "brush": "Brush",
        "clone": "Clone",
        "far-clone": "Clone",
        "copy": "Copy",
        "far-copy": "Copy",
        "crop": "Crop",
        "crop-alt": "Crop Alt",
        "crosshairs": "Crosshairs",
        "cut": "Cut",
        "drafting-compass": "Drafting Compass",
        "draw-polygon": "Draw Polygon",
        "edit": "Edit",
        "far-edit": "Edit",
        "eraser": "Eraser",
        "eye": "Eye",
        "far-eye": "Eye",
        "eye-dropper": "Eye Dropper",
        "eye-slash": "Eye Slash",
        "far-eye-slash": "Eye Slash",
        "fill": "Fill",
        "fill-drip": "Fill Drip",
        "highlighter": "Highlighter",
        "layer-group": "Layer Group",
        "magic": "Magic",
        "marker": "Marker",
        "object-group": "Object Group",
        "far-object-group": "Object Group",
        "object-ungroup": "Object Ungroup",
        "far-object-ungroup": "Object Ungroup",
        "paint-brush": "Paint Brush",
        "paint-roller": "Paint Roller",
        "palette": "Palette",
        "paste": "Paste",
        "pen": "Pen",
        "pen-alt": "Pen Alt",
        "pen-fancy": "Pen Fancy",
        "pen-nib": "Pen Nib",
        "pencil-alt": "Pencil Alt",
        "pencil-ruler": "Pencil Ruler",
        "ruler-combined": "Ruler Combined",
        "ruler-horizontal": "Ruler Horizontal",
        "ruler-vertical": "Ruler Vertical",
        "save": "Save",
        "far-save": "Save",
        "splotch": "Splotch",
        "spray-can": "Spray Can",
        "stamp": "Stamp",
        "swatchbook": "Swatchbook",
        "tint": "Tint",
        "tint-slash": "Tint Slash",
        "vector-square": "Vector Square"
    },
    "Editors": {
        "align-center": "Align Center",
        "align-justify": "Align Justify",
        "align-left": "Align Left",
        "align-right": "Align Right",
        "bold": "Bold",
        "clipboard": "Clipboard",
        "far-clipboard": "Clipboard",
        "clone": "Clone",
        "far-clone": "Clone",
        "columns": "Columns",
        "copy": "Copy",
        "far-copy": "Copy",
        "cut": "Cut",
        "edit": "Edit",
        "far-edit": "Edit",
        "eraser": "Eraser",
        "file": "File",
        "far-file": "File",
        "file-alt": "File Alt",
        "far-file-alt": "File Alt",
        "font": "Font",
        "glasses": "Glasses",
        "heading": "Heading",
        "highlighter": "Highlighter",
        "i-cursor": "I Cursor",
        "indent": "Indent",
        "italic": "Italic",
        "link": "Link",
        "list": "List",
        "list-alt": "List Alt",
        "far-list-alt": "List Alt",
        "list-ol": "List Ol",
        "list-ul": "List Ul",
        "marker": "Marker",
        "outdent": "Outdent",
        "paper-plane": "Paper Plane",
        "far-paper-plane": "Paper Plane",
        "paperclip": "Paperclip",
        "paragraph": "Paragraph",
        "paste": "Paste",
        "pen": "Pen",
        "pen-alt": "Pen Alt",
        "pen-fancy": "Pen Fancy",
        "pen-nib": "Pen Nib",
        "pencil-alt": "Pencil Alt",
        "print": "Print",
        "quote-left": "Quote Left",
        "quote-right": "Quote Right",
        "redo": "Redo",
        "redo-alt": "Redo Alt",
        "reply": "Reply",
        "reply-all": "Reply All",
        "screwdriver": "Screwdriver",
        "share": "Share",
        "strikethrough": "Strikethrough",
        "subscript": "Subscript",
        "superscript": "Superscript",
        "sync": "Sync",
        "sync-alt": "Sync Alt",
        "table": "Table",
        "tasks": "Tasks",
        "text-height": "Text Height",
        "text-width": "Text Width",
        "th": "Th",
        "th-large": "Th Large",
        "th-list": "Th List",
        "tools": "Tools",
        "trash": "Trash",
        "trash-alt": "Trash Alt",
        "far-trash-alt": "Trash Alt",
        "trash-restore": "Trash Restore",
        "trash-restore-alt": "Trash Restore Alt",
        "underline": "Underline",
        "undo": "Undo",
        "undo-alt": "Undo Alt",
        "unlink": "Unlink",
        "wrench": "Wrench"
    },
    "Education": {
        "apple-alt": "Apple Alt",
        "atom": "Atom",
        "award": "Award",
        "bell": "Bell",
        "far-bell": "Bell",
        "bell-slash": "Bell Slash",
        "far-bell-slash": "Bell Slash",
        "book-open": "Book Open",
        "book-reader": "Book Reader",
        "chalkboard": "Chalkboard",
        "chalkboard-teacher": "Chalkboard Teacher",
        "graduation-cap": "Graduation Cap",
        "laptop-code": "Laptop Code",
        "microscope": "Microscope",
        "music": "Music",
        "school": "School",
        "shapes": "Shapes",
        "theater-masks": "Theater Masks",
        "user-graduate": "User Graduate"
    },
    "Emoji": {
        "angry": "Angry",
        "far-angry": "Angry",
        "dizzy": "Dizzy",
        "far-dizzy": "Dizzy",
        "flushed": "Flushed",
        "far-flushed": "Flushed",
        "frown": "Frown",
        "far-frown": "Frown",
        "frown-open": "Frown Open",
        "far-frown-open": "Frown Open",
        "grimace": "Grimace",
        "far-grimace": "Grimace",
        "grin": "Grin",
        "far-grin": "Grin",
        "grin-alt": "Grin Alt",
        "far-grin-alt": "Grin Alt",
        "grin-beam": "Grin Beam",
        "far-grin-beam": "Grin Beam",
        "grin-beam-sweat": "Grin Beam Sweat",
        "far-grin-beam-sweat": "Grin Beam Sweat",
        "grin-hearts": "Grin Hearts",
        "far-grin-hearts": "Grin Hearts",
        "grin-squint": "Grin Squint",
        "far-grin-squint": "Grin Squint",
        "grin-squint-tears": "Grin Squint Tears",
        "far-grin-squint-tears": "Grin Squint Tears",
        "grin-stars": "Grin Stars",
        "far-grin-stars": "Grin Stars",
        "grin-tears": "Grin Tears",
        "far-grin-tears": "Grin Tears",
        "grin-tongue": "Grin Tongue",
        "far-grin-tongue": "Grin Tongue",
        "grin-tongue-squint": "Grin Tongue Squint",
        "far-grin-tongue-squint": "Grin Tongue Squint",
        "grin-tongue-wink": "Grin Tongue Wink",
        "far-grin-tongue-wink": "Grin Tongue Wink",
        "grin-wink": "Grin Wink",
        "far-grin-wink": "Grin Wink",
        "kiss": "Kiss",
        "far-kiss": "Kiss",
        "kiss-beam": "Kiss Beam",
        "far-kiss-beam": "Kiss Beam",
        "kiss-wink-heart": "Kiss Wink Heart",
        "far-kiss-wink-heart": "Kiss Wink Heart",
        "laugh": "Laugh",
        "far-laugh": "Laugh",
        "laugh-beam": "Laugh Beam",
        "far-laugh-beam": "Laugh Beam",
        "laugh-squint": "Laugh Squint",
        "far-laugh-squint": "Laugh Squint",
        "laugh-wink": "Laugh Wink",
        "far-laugh-wink": "Laugh Wink",
        "meh": "Meh",
        "far-meh": "Meh",
        "meh-blank": "Meh Blank",
        "far-meh-blank": "Meh Blank",
        "meh-rolling-eyes": "Meh Rolling Eyes",
        "far-meh-rolling-eyes": "Meh Rolling Eyes",
        "sad-cry": "Sad Cry",
        "far-sad-cry": "Sad Cry",
        "sad-tear": "Sad Tear",
        "far-sad-tear": "Sad Tear",
        "smile": "Smile",
        "far-smile": "Smile",
        "smile-beam": "Smile Beam",
        "far-smile-beam": "Smile Beam",
        "smile-wink": "Smile Wink",
        "far-smile-wink": "Smile Wink",
        "surprise": "Surprise",
        "far-surprise": "Surprise",
        "tired": "Tired",
        "far-tired": "Tired"
    },
    "Files": {
        "archive": "Archive",
        "clone": "Clone",
        "far-clone": "Clone",
        "copy": "Copy",
        "far-copy": "Copy",
        "cut": "Cut",
        "file": "File",
        "far-file": "File",
        "file-alt": "File Alt",
        "far-file-alt": "File Alt",
        "file-archive": "File Archive",
        "far-file-archive": "File Archive",
        "file-audio": "File Audio",
        "far-file-audio": "File Audio",
        "file-code": "File Code",
        "far-file-code": "File Code",
        "file-excel": "File Excel",
        "far-file-excel": "File Excel",
        "file-image": "File Image",
        "far-file-image": "File Image",
        "file-pdf": "File Pdf",
        "far-file-pdf": "File Pdf",
        "file-powerpoint": "File Powerpoint",
        "far-file-powerpoint": "File Powerpoint",
        "file-video": "File Video",
        "far-file-video": "File Video",
        "file-word": "File Word",
        "far-file-word": "File Word",
        "folder": "Folder",
        "far-folder": "Folder",
        "folder-open": "Folder Open",
        "far-folder-open": "Folder Open",
        "paste": "Paste",
        "save": "Save",
        "far-save": "Save",
        "sticky-note": "Sticky Note",
        "far-sticky-note": "Sticky Note"
    },
    "Food": {
        "apple-alt": "Apple Alt",
        "bacon": "Bacon",
        "bone": "Bone",
        "bread-slice": "Bread Slice",
        "candy-cane": "Candy Cane",
        "carrot": "Carrot",
        "cheese": "Cheese",
        "cloud-meatball": "Cloud Meatball",
        "cookie": "Cookie",
        "drumstick-bite": "Drumstick Bite",
        "egg": "Egg",
        "fish": "Fish",
        "hamburger": "Hamburger",
        "hotdog": "Hotdog",
        "ice-cream": "Ice Cream",
        "lemon": "Lemon",
        "far-lemon": "Lemon",
        "pepper-hot": "Pepper Hot",
        "pizza-slice": "Pizza Slice",
        "seedling": "Seedling",
        "stroopwafel": "Stroopwafel"
    },
    "Genders": {
        "genderless": "Genderless",
        "mars": "Mars",
        "mars-double": "Mars Double",
        "mars-stroke": "Mars Stroke",
        "mars-stroke-h": "Mars Stroke H",
        "mars-stroke-v": "Mars Stroke V",
        "mercury": "Mercury",
        "neuter": "Neuter",
        "transgender": "Transgender",
        "transgender-alt": "Transgender Alt",
        "venus": "Venus",
        "venus-double": "Venus Double",
        "venus-mars": "Venus Mars"
    },
    "Halloween": {
        "book-dead": "Book Dead",
        "broom": "Broom",
        "cat": "Cat",
        "cloud-moon": "Cloud Moon",
        "crow": "Crow",
        "ghost": "Ghost",
        "hat-wizard": "Hat Wizard",
        "mask": "Mask",
        "skull-crossbones": "Skull Crossbones",
        "spider": "Spider",
        "toilet-paper": "Toilet Paper"
    },
    "Hands": {
        "allergies": "Allergies",
        "fist-raised": "Fist Raised",
        "hand-holding": "Hand Holding",
        "hand-holding-heart": "Hand Holding Heart",
        "hand-holding-usd": "Hand Holding Usd",
        "hand-lizard": "Hand Lizard",
        "far-hand-lizard": "Hand Lizard",
        "hand-middle-finger": "Hand Middle Finger",
        "hand-paper": "Hand Paper",
        "far-hand-paper": "Hand Paper",
        "hand-peace": "Hand Peace",
        "far-hand-peace": "Hand Peace",
        "hand-point-down": "Hand Point Down",
        "far-hand-point-down": "Hand Point Down",
        "hand-point-left": "Hand Point Left",
        "far-hand-point-left": "Hand Point Left",
        "hand-point-right": "Hand Point Right",
        "far-hand-point-right": "Hand Point Right",
        "hand-point-up": "Hand Point Up",
        "far-hand-point-up": "Hand Point Up",
        "hand-pointer": "Hand Pointer",
        "far-hand-pointer": "Hand Pointer",
        "hand-rock": "Hand Rock",
        "far-hand-rock": "Hand Rock",
        "hand-scissors": "Hand Scissors",
        "far-hand-scissors": "Hand Scissors",
        "hand-spock": "Hand Spock",
        "far-hand-spock": "Hand Spock",
        "hands": "Hands",
        "hands-helping": "Hands Helping",
        "handshake": "Handshake",
        "far-handshake": "Handshake",
        "praying-hands": "Praying Hands",
        "thumbs-down": "Thumbs Down",
        "far-thumbs-down": "Thumbs Down",
        "thumbs-up": "Thumbs Up",
        "far-thumbs-up": "Thumbs Up"
    },
    "Health": {
        "ambulance": "Ambulance",
        "h-square": "H Square",
        "heart": "Heart",
        "far-heart": "Heart",
        "heartbeat": "Heartbeat",
        "hospital": "Hospital",
        "far-hospital": "Hospital",
        "medkit": "Medkit",
        "plus-square": "Plus Square",
        "far-plus-square": "Plus Square",
        "prescription": "Prescription",
        "stethoscope": "Stethoscope",
        "user-md": "User Md",
        "wheelchair": "Wheelchair"
    },
    "Holiday": {
        "candy-cane": "Candy Cane",
        "carrot": "Carrot",
        "cookie-bite": "Cookie Bite",
        "gift": "Gift",
        "gifts": "Gifts",
        "glass-cheers": "Glass Cheers",
        "holly-berry": "Holly Berry",
        "mug-hot": "Mug Hot",
        "sleigh": "Sleigh",
        "snowman": "Snowman"
    },
    "Images": {
        "adjust": "Adjust",
        "bolt": "Bolt",
        "camera": "Camera",
        "camera-retro": "Camera Retro",
        "chalkboard": "Chalkboard",
        "clone": "Clone",
        "far-clone": "Clone",
        "compress": "Compress",
        "compress-arrows-alt": "Compress Arrows Alt",
        "expand": "Expand",
        "eye": "Eye",
        "far-eye": "Eye",
        "eye-dropper": "Eye Dropper",
        "eye-slash": "Eye Slash",
        "far-eye-slash": "Eye Slash",
        "file-image": "File Image",
        "far-file-image": "File Image",
        "film": "Film",
        "id-badge": "Id Badge",
        "far-id-badge": "Id Badge",
        "id-card": "Id Card",
        "far-id-card": "Id Card",
        "image": "Image",
        "far-image": "Image",
        "images": "Images",
        "far-images": "Images",
        "portrait": "Portrait",
        "sliders-h": "Sliders H",
        "tint": "Tint"
    },
    "Interfaces": {
        "award": "Award",
        "ban": "Ban",
        "barcode": "Barcode",
        "bars": "Bars",
        "beer": "Beer",
        "bell": "Bell",
        "far-bell": "Bell",
        "bell-slash": "Bell Slash",
        "far-bell-slash": "Bell Slash",
        "blog": "Blog",
        "bug": "Bug",
        "bullhorn": "Bullhorn",
        "bullseye": "Bullseye",
        "calculator": "Calculator",
        "calendar": "Calendar",
        "far-calendar": "Calendar",
        "calendar-alt": "Calendar Alt",
        "far-calendar-alt": "Calendar Alt",
        "calendar-check": "Calendar Check",
        "far-calendar-check": "Calendar Check",
        "calendar-minus": "Calendar Minus",
        "far-calendar-minus": "Calendar Minus",
        "calendar-plus": "Calendar Plus",
        "far-calendar-plus": "Calendar Plus",
        "calendar-times": "Calendar Times",
        "far-calendar-times": "Calendar Times",
        "certificate": "Certificate",
        "check": "Check",
        "check-circle": "Check Circle",
        "far-check-circle": "Check Circle",
        "check-double": "Check Double",
        "check-square": "Check Square",
        "far-check-square": "Check Square",
        "circle": "Circle",
        "far-circle": "Circle",
        "clipboard": "Clipboard",
        "far-clipboard": "Clipboard",
        "clone": "Clone",
        "far-clone": "Clone",
        "cloud": "Cloud",
        "cloud-download-alt": "Cloud Download Alt",
        "cloud-upload-alt": "Cloud Upload Alt",
        "coffee": "Coffee",
        "cog": "Cog",
        "cogs": "Cogs",
        "copy": "Copy",
        "far-copy": "Copy",
        "cut": "Cut",
        "database": "Database",
        "dot-circle": "Dot Circle",
        "far-dot-circle": "Dot Circle",
        "download": "Download",
        "edit": "Edit",
        "far-edit": "Edit",
        "ellipsis-h": "Ellipsis H",
        "ellipsis-v": "Ellipsis V",
        "envelope": "Envelope",
        "far-envelope": "Envelope",
        "envelope-open": "Envelope Open",
        "far-envelope-open": "Envelope Open",
        "eraser": "Eraser",
        "exclamation": "Exclamation",
        "exclamation-circle": "Exclamation Circle",
        "exclamation-triangle": "Exclamation Triangle",
        "external-link-alt": "External Link Alt",
        "external-link-square-alt": "External Link Square Alt",
        "eye": "Eye",
        "far-eye": "Eye",
        "eye-slash": "Eye Slash",
        "far-eye-slash": "Eye Slash",
        "file": "File",
        "far-file": "File",
        "file-alt": "File Alt",
        "far-file-alt": "File Alt",
        "file-download": "File Download",
        "file-export": "File Export",
        "file-import": "File Import",
        "file-upload": "File Upload",
        "filter": "Filter",
        "fingerprint": "Fingerprint",
        "flag": "Flag",
        "far-flag": "Flag",
        "flag-checkered": "Flag Checkered",
        "folder": "Folder",
        "far-folder": "Folder",
        "folder-open": "Folder Open",
        "far-folder-open": "Folder Open",
        "frown": "Frown",
        "far-frown": "Frown",
        "glasses": "Glasses",
        "grip-horizontal": "Grip Horizontal",
        "grip-lines": "Grip Lines",
        "grip-lines-vertical": "Grip Lines Vertical",
        "grip-vertical": "Grip Vertical",
        "hashtag": "Hashtag",
        "heart": "Heart",
        "far-heart": "Heart",
        "history": "History",
        "home": "Home",
        "i-cursor": "I Cursor",
        "info": "Info",
        "info-circle": "Info Circle",
        "language": "Language",
        "magic": "Magic",
        "marker": "Marker",
        "medal": "Medal",
        "meh": "Meh",
        "far-meh": "Meh",
        "microphone": "Microphone",
        "microphone-alt": "Microphone Alt",
        "microphone-slash": "Microphone Slash",
        "minus": "Minus",
        "minus-circle": "Minus Circle",
        "minus-square": "Minus Square",
        "far-minus-square": "Minus Square",
        "paste": "Paste",
        "pen": "Pen",
        "pen-alt": "Pen Alt",
        "pen-fancy": "Pen Fancy",
        "pencil-alt": "Pencil Alt",
        "plus": "Plus",
        "plus-circle": "Plus Circle",
        "plus-square": "Plus Square",
        "far-plus-square": "Plus Square",
        "poo": "Poo",
        "qrcode": "Qrcode",
        "question": "Question",
        "question-circle": "Question Circle",
        "far-question-circle": "Question Circle",
        "quote-left": "Quote Left",
        "quote-right": "Quote Right",
        "redo": "Redo",
        "redo-alt": "Redo Alt",
        "reply": "Reply",
        "reply-all": "Reply All",
        "rss": "Rss",
        "rss-square": "Rss Square",
        "save": "Save",
        "far-save": "Save",
        "screwdriver": "Screwdriver",
        "search": "Search",
        "search-minus": "Search Minus",
        "search-plus": "Search Plus",
        "share": "Share",
        "share-alt": "Share Alt",
        "share-alt-square": "Share Alt Square",
        "share-square": "Share Square",
        "far-share-square": "Share Square",
        "shield-alt": "Shield Alt",
        "sign-in-alt": "Sign In Alt",
        "sign-out-alt": "Sign Out Alt",
        "signal": "Signal",
        "sitemap": "Sitemap",
        "sliders-h": "Sliders H",
        "smile": "Smile",
        "far-smile": "Smile",
        "sort": "Sort",
        "sort-alpha-down": "Sort Alpha Down",
        "sort-alpha-up": "Sort Alpha Up",
        "sort-amount-down": "Sort Amount Down",
        "sort-amount-up": "Sort Amount Up",
        "sort-down": "Sort Down",
        "sort-numeric-down": "Sort Numeric Down",
        "sort-numeric-up": "Sort Numeric Up",
        "sort-up": "Sort Up",
        "star": "Star",
        "far-star": "Star",
        "star-half": "Star Half",
        "far-star-half": "Star Half",
        "sync": "Sync",
        "sync-alt": "Sync Alt",
        "thumbs-down": "Thumbs Down",
        "far-thumbs-down": "Thumbs Down",
        "thumbs-up": "Thumbs Up",
        "far-thumbs-up": "Thumbs Up",
        "times": "Times",
        "times-circle": "Times Circle",
        "far-times-circle": "Times Circle",
        "toggle-off": "Toggle Off",
        "toggle-on": "Toggle On",
        "tools": "Tools",
        "trash": "Trash",
        "trash-alt": "Trash Alt",
        "far-trash-alt": "Trash Alt",
        "trash-restore": "Trash Restore",
        "trash-restore-alt": "Trash Restore Alt",
        "trophy": "Trophy",
        "undo": "Undo",
        "undo-alt": "Undo Alt",
        "upload": "Upload",
        "user": "User",
        "far-user": "User",
        "user-alt": "User Alt",
        "user-circle": "User Circle",
        "far-user-circle": "User Circle",
        "volume-down": "Volume Down",
        "volume-mute": "Volume Mute",
        "volume-off": "Volume Off",
        "volume-up": "Volume Up",
        "wifi": "Wifi",
        "wrench": "Wrench"
    },
    "Logistics": {
        "box": "Box",
        "boxes": "Boxes",
        "clipboard-check": "Clipboard Check",
        "clipboard-list": "Clipboard List",
        "dolly": "Dolly",
        "dolly-flatbed": "Dolly Flatbed",
        "hard-hat": "Hard Hat",
        "pallet": "Pallet",
        "shipping-fast": "Shipping Fast",
        "truck": "Truck",
        "warehouse": "Warehouse"
    },
    "Maps": {
        "ambulance": "Ambulance",
        "anchor": "Anchor",
        "balance-scale": "Balance Scale",
        "bath": "Bath",
        "bed": "Bed",
        "beer": "Beer",
        "bell": "Bell",
        "far-bell": "Bell",
        "bell-slash": "Bell Slash",
        "far-bell-slash": "Bell Slash",
        "bicycle": "Bicycle",
        "binoculars": "Binoculars",
        "birthday-cake": "Birthday Cake",
        "blind": "Blind",
        "bomb": "Bomb",
        "book": "Book",
        "bookmark": "Bookmark",
        "far-bookmark": "Bookmark",
        "briefcase": "Briefcase",
        "building": "Building",
        "far-building": "Building",
        "car": "Car",
        "coffee": "Coffee",
        "crosshairs": "Crosshairs",
        "directions": "Directions",
        "dollar-sign": "Dollar Sign",
        "draw-polygon": "Draw Polygon",
        "eye": "Eye",
        "far-eye": "Eye",
        "eye-slash": "Eye Slash",
        "far-eye-slash": "Eye Slash",
        "fighter-jet": "Fighter Jet",
        "fire": "Fire",
        "fire-alt": "Fire Alt",
        "fire-extinguisher": "Fire Extinguisher",
        "flag": "Flag",
        "far-flag": "Flag",
        "flag-checkered": "Flag Checkered",
        "flask": "Flask",
        "gamepad": "Gamepad",
        "gavel": "Gavel",
        "gift": "Gift",
        "glass-martini": "Glass Martini",
        "globe": "Globe",
        "graduation-cap": "Graduation Cap",
        "h-square": "H Square",
        "heart": "Heart",
        "far-heart": "Heart",
        "heartbeat": "Heartbeat",
        "helicopter": "Helicopter",
        "home": "Home",
        "hospital": "Hospital",
        "far-hospital": "Hospital",
        "image": "Image",
        "far-image": "Image",
        "images": "Images",
        "far-images": "Images",
        "industry": "Industry",
        "info": "Info",
        "info-circle": "Info Circle",
        "key": "Key",
        "landmark": "Landmark",
        "layer-group": "Layer Group",
        "leaf": "Leaf",
        "lemon": "Lemon",
        "far-lemon": "Lemon",
        "life-ring": "Life Ring",
        "far-life-ring": "Life Ring",
        "lightbulb": "Lightbulb",
        "far-lightbulb": "Lightbulb",
        "location-arrow": "Location Arrow",
        "low-vision": "Low Vision",
        "magnet": "Magnet",
        "male": "Male",
        "map": "Map",
        "far-map": "Map",
        "map-marker": "Map Marker",
        "map-marker-alt": "Map Marker Alt",
        "map-pin": "Map Pin",
        "map-signs": "Map Signs",
        "medkit": "Medkit",
        "money-bill": "Money Bill",
        "money-bill-alt": "Money Bill Alt",
        "far-money-bill-alt": "Money Bill Alt",
        "motorcycle": "Motorcycle",
        "music": "Music",
        "newspaper": "Newspaper",
        "far-newspaper": "Newspaper",
        "parking": "Parking",
        "paw": "Paw",
        "phone": "Phone",
        "phone-square": "Phone Square",
        "phone-volume": "Phone Volume",
        "plane": "Plane",
        "plug": "Plug",
        "plus": "Plus",
        "plus-square": "Plus Square",
        "far-plus-square": "Plus Square",
        "print": "Print",
        "recycle": "Recycle",
        "restroom": "Restroom",
        "road": "Road",
        "rocket": "Rocket",
        "route": "Route",
        "search": "Search",
        "search-minus": "Search Minus",
        "search-plus": "Search Plus",
        "ship": "Ship",
        "shoe-prints": "Shoe Prints",
        "shopping-bag": "Shopping Bag",
        "shopping-basket": "Shopping Basket",
        "shopping-cart": "Shopping Cart",
        "shower": "Shower",
        "snowplow": "Snowplow",
        "street-view": "Street View",
        "subway": "Subway",
        "suitcase": "Suitcase",
        "tag": "Tag",
        "tags": "Tags",
        "taxi": "Taxi",
        "thumbtack": "Thumbtack",
        "ticket-alt": "Ticket Alt",
        "tint": "Tint",
        "traffic-light": "Traffic Light",
        "train": "Train",
        "tram": "Tram",
        "tree": "Tree",
        "trophy": "Trophy",
        "truck": "Truck",
        "tty": "Tty",
        "umbrella": "Umbrella",
        "university": "University",
        "utensil-spoon": "Utensil Spoon",
        "utensils": "Utensils",
        "wheelchair": "Wheelchair",
        "wifi": "Wifi",
        "wine-glass": "Wine Glass",
        "wrench": "Wrench"
    },
    "Marketing": {
        "ad": "Ad",
        "bullhorn": "Bullhorn",
        "bullseye": "Bullseye",
        "comment-dollar": "Comment Dollar",
        "comments-dollar": "Comments Dollar",
        "envelope-open-text": "Envelope Open Text",
        "funnel-dollar": "Funnel Dollar",
        "lightbulb": "Lightbulb",
        "far-lightbulb": "Lightbulb",
        "mail-bulk": "Mail Bulk",
        "poll": "Poll",
        "poll-h": "Poll H",
        "search-dollar": "Search Dollar",
        "search-location": "Search Location"
    },
    "Mathematics": {
        "calculator": "Calculator",
        "divide": "Divide",
        "equals": "Equals",
        "greater-than": "Greater Than",
        "greater-than-equal": "Greater Than Equal",
        "infinity": "Infinity",
        "less-than": "Less Than",
        "less-than-equal": "Less Than Equal",
        "minus": "Minus",
        "not-equal": "Not Equal",
        "percentage": "Percentage",
        "plus": "Plus",
        "square-root-alt": "Square Root Alt",
        "subscript": "Subscript",
        "superscript": "Superscript",
        "times": "Times"
    },
    "Medical": {
        "allergies": "Allergies",
        "ambulance": "Ambulance",
        "band-aid": "Band Aid",
        "biohazard": "Biohazard",
        "bone": "Bone",
        "bong": "Bong",
        "book-medical": "Book Medical",
        "brain": "Brain",
        "briefcase-medical": "Briefcase Medical",
        "burn": "Burn",
        "cannabis": "Cannabis",
        "capsules": "Capsules",
        "clinic-medical": "Clinic Medical",
        "comment-medical": "Comment Medical",
        "crutch": "Crutch",
        "diagnoses": "Diagnoses",
        "dna": "Dna",
        "file-medical": "File Medical",
        "file-medical-alt": "File Medical Alt",
        "file-prescription": "File Prescription",
        "first-aid": "First Aid",
        "heart": "Heart",
        "far-heart": "Heart",
        "heartbeat": "Heartbeat",
        "hospital": "Hospital",
        "far-hospital": "Hospital",
        "hospital-alt": "Hospital Alt",
        "hospital-symbol": "Hospital Symbol",
        "id-card-alt": "Id Card Alt",
        "joint": "Joint",
        "laptop-medical": "Laptop Medical",
        "microscope": "Microscope",
        "mortar-pestle": "Mortar Pestle",
        "notes-medical": "Notes Medical",
        "pager": "Pager",
        "pills": "Pills",
        "plus": "Plus",
        "poop": "Poop",
        "prescription": "Prescription",
        "prescription-bottle": "Prescription Bottle",
        "prescription-bottle-alt": "Prescription Bottle Alt",
        "procedures": "Procedures",
        "radiation": "Radiation",
        "radiation-alt": "Radiation Alt",
        "smoking": "Smoking",
        "smoking-ban": "Smoking Ban",
        "star-of-life": "Star Of Life",
        "stethoscope": "Stethoscope",
        "syringe": "Syringe",
        "tablets": "Tablets",
        "teeth": "Teeth",
        "teeth-open": "Teeth Open",
        "thermometer": "Thermometer",
        "tooth": "Tooth",
        "user-md": "User Md",
        "user-nurse": "User Nurse",
        "vial": "Vial",
        "vials": "Vials",
        "weight": "Weight",
        "x-ray": "X Ray"
    },
    "Moving": {
        "archive": "Archive",
        "box-open": "Box Open",
        "couch": "Couch",
        "dolly": "Dolly",
        "people-carry": "People Carry",
        "route": "Route",
        "sign": "Sign",
        "suitcase": "Suitcase",
        "tape": "Tape",
        "truck-loading": "Truck Loading",
        "truck-moving": "Truck Moving",
        "wine-glass": "Wine Glass"
    },
    "Objects": {
        "ambulance": "Ambulance",
        "anchor": "Anchor",
        "archive": "Archive",
        "award": "Award",
        "baby-carriage": "Baby Carriage",
        "balance-scale": "Balance Scale",
        "bath": "Bath",
        "bed": "Bed",
        "beer": "Beer",
        "bell": "Bell",
        "far-bell": "Bell",
        "bicycle": "Bicycle",
        "binoculars": "Binoculars",
        "birthday-cake": "Birthday Cake",
        "blender": "Blender",
        "bomb": "Bomb",
        "book": "Book",
        "book-dead": "Book Dead",
        "bookmark": "Bookmark",
        "far-bookmark": "Bookmark",
        "briefcase": "Briefcase",
        "broadcast-tower": "Broadcast Tower",
        "bug": "Bug",
        "building": "Building",
        "far-building": "Building",
        "bullhorn": "Bullhorn",
        "bullseye": "Bullseye",
        "bus": "Bus",
        "calculator": "Calculator",
        "calendar": "Calendar",
        "far-calendar": "Calendar",
        "calendar-alt": "Calendar Alt",
        "far-calendar-alt": "Calendar Alt",
        "camera": "Camera",
        "camera-retro": "Camera Retro",
        "candy-cane": "Candy Cane",
        "car": "Car",
        "carrot": "Carrot",
        "church": "Church",
        "clipboard": "Clipboard",
        "far-clipboard": "Clipboard",
        "cloud": "Cloud",
        "coffee": "Coffee",
        "cog": "Cog",
        "cogs": "Cogs",
        "compass": "Compass",
        "far-compass": "Compass",
        "cookie": "Cookie",
        "cookie-bite": "Cookie Bite",
        "copy": "Copy",
        "far-copy": "Copy",
        "cube": "Cube",
        "cubes": "Cubes",
        "cut": "Cut",
        "dice": "Dice",
        "dice-d20": "Dice D20",
        "dice-d6": "Dice D6",
        "dice-five": "Dice Five",
        "dice-four": "Dice Four",
        "dice-one": "Dice One",
        "dice-six": "Dice Six",
        "dice-three": "Dice Three",
        "dice-two": "Dice Two",
        "digital-tachograph": "Digital Tachograph",
        "door-closed": "Door Closed",
        "door-open": "Door Open",
        "drum": "Drum",
        "drum-steelpan": "Drum Steelpan",
        "envelope": "Envelope",
        "far-envelope": "Envelope",
        "envelope-open": "Envelope Open",
        "far-envelope-open": "Envelope Open",
        "eraser": "Eraser",
        "eye": "Eye",
        "far-eye": "Eye",
        "eye-dropper": "Eye Dropper",
        "fax": "Fax",
        "feather": "Feather",
        "feather-alt": "Feather Alt",
        "fighter-jet": "Fighter Jet",
        "file": "File",
        "far-file": "File",
        "file-alt": "File Alt",
        "far-file-alt": "File Alt",
        "file-prescription": "File Prescription",
        "film": "Film",
        "fire": "Fire",
        "fire-alt": "Fire Alt",
        "fire-extinguisher": "Fire Extinguisher",
        "flag": "Flag",
        "far-flag": "Flag",
        "flag-checkered": "Flag Checkered",
        "flask": "Flask",
        "futbol": "Futbol",
        "far-futbol": "Futbol",
        "gamepad": "Gamepad",
        "gavel": "Gavel",
        "gem": "Gem",
        "far-gem": "Gem",
        "gift": "Gift",
        "gifts": "Gifts",
        "glass-cheers": "Glass Cheers",
        "glass-martini": "Glass Martini",
        "glass-whiskey": "Glass Whiskey",
        "glasses": "Glasses",
        "globe": "Globe",
        "graduation-cap": "Graduation Cap",
        "guitar": "Guitar",
        "hat-wizard": "Hat Wizard",
        "hdd": "Hdd",
        "far-hdd": "Hdd",
        "headphones": "Headphones",
        "headphones-alt": "Headphones Alt",
        "headset": "Headset",
        "heart": "Heart",
        "far-heart": "Heart",
        "heart-broken": "Heart Broken",
        "helicopter": "Helicopter",
        "highlighter": "Highlighter",
        "holly-berry": "Holly Berry",
        "home": "Home",
        "hospital": "Hospital",
        "far-hospital": "Hospital",
        "hourglass": "Hourglass",
        "far-hourglass": "Hourglass",
        "igloo": "Igloo",
        "image": "Image",
        "far-image": "Image",
        "images": "Images",
        "far-images": "Images",
        "industry": "Industry",
        "key": "Key",
        "keyboard": "Keyboard",
        "far-keyboard": "Keyboard",
        "laptop": "Laptop",
        "leaf": "Leaf",
        "lemon": "Lemon",
        "far-lemon": "Lemon",
        "life-ring": "Life Ring",
        "far-life-ring": "Life Ring",
        "lightbulb": "Lightbulb",
        "far-lightbulb": "Lightbulb",
        "lock": "Lock",
        "lock-open": "Lock Open",
        "magic": "Magic",
        "magnet": "Magnet",
        "map": "Map",
        "far-map": "Map",
        "map-marker": "Map Marker",
        "map-marker-alt": "Map Marker Alt",
        "map-pin": "Map Pin",
        "map-signs": "Map Signs",
        "marker": "Marker",
        "medal": "Medal",
        "medkit": "Medkit",
        "memory": "Memory",
        "microchip": "Microchip",
        "microphone": "Microphone",
        "microphone-alt": "Microphone Alt",
        "mitten": "Mitten",
        "mobile": "Mobile",
        "mobile-alt": "Mobile Alt",
        "money-bill": "Money Bill",
        "money-bill-alt": "Money Bill Alt",
        "far-money-bill-alt": "Money Bill Alt",
        "money-check": "Money Check",
        "money-check-alt": "Money Check Alt",
        "moon": "Moon",
        "far-moon": "Moon",
        "motorcycle": "Motorcycle",
        "mug-hot": "Mug Hot",
        "newspaper": "Newspaper",
        "far-newspaper": "Newspaper",
        "paint-brush": "Paint Brush",
        "paper-plane": "Paper Plane",
        "far-paper-plane": "Paper Plane",
        "paperclip": "Paperclip",
        "paste": "Paste",
        "paw": "Paw",
        "pen": "Pen",
        "pen-alt": "Pen Alt",
        "pen-fancy": "Pen Fancy",
        "pen-nib": "Pen Nib",
        "pencil-alt": "Pencil Alt",
        "phone": "Phone",
        "plane": "Plane",
        "plug": "Plug",
        "print": "Print",
        "puzzle-piece": "Puzzle Piece",
        "ring": "Ring",
        "road": "Road",
        "rocket": "Rocket",
        "ruler-combined": "Ruler Combined",
        "ruler-horizontal": "Ruler Horizontal",
        "ruler-vertical": "Ruler Vertical",
        "satellite": "Satellite",
        "satellite-dish": "Satellite Dish",
        "save": "Save",
        "far-save": "Save",
        "school": "School",
        "screwdriver": "Screwdriver",
        "scroll": "Scroll",
        "sd-card": "Sd Card",
        "search": "Search",
        "shield-alt": "Shield Alt",
        "shopping-bag": "Shopping Bag",
        "shopping-basket": "Shopping Basket",
        "shopping-cart": "Shopping Cart",
        "shower": "Shower",
        "sim-card": "Sim Card",
        "skull-crossbones": "Skull Crossbones",
        "sleigh": "Sleigh",
        "snowflake": "Snowflake",
        "far-snowflake": "Snowflake",
        "snowplow": "Snowplow",
        "space-shuttle": "Space Shuttle",
        "star": "Star",
        "far-star": "Star",
        "sticky-note": "Sticky Note",
        "far-sticky-note": "Sticky Note",
        "stopwatch": "Stopwatch",
        "stroopwafel": "Stroopwafel",
        "subway": "Subway",
        "suitcase": "Suitcase",
        "sun": "Sun",
        "far-sun": "Sun",
        "tablet": "Tablet",
        "tablet-alt": "Tablet Alt",
        "tachometer-alt": "Tachometer Alt",
        "tag": "Tag",
        "tags": "Tags",
        "taxi": "Taxi",
        "thumbtack": "Thumbtack",
        "ticket-alt": "Ticket Alt",
        "toilet": "Toilet",
        "toolbox": "Toolbox",
        "tools": "Tools",
        "train": "Train",
        "tram": "Tram",
        "trash": "Trash",
        "trash-alt": "Trash Alt",
        "far-trash-alt": "Trash Alt",
        "tree": "Tree",
        "trophy": "Trophy",
        "truck": "Truck",
        "tv": "Tv",
        "umbrella": "Umbrella",
        "university": "University",
        "unlock": "Unlock",
        "unlock-alt": "Unlock Alt",
        "utensil-spoon": "Utensil Spoon",
        "utensils": "Utensils",
        "wallet": "Wallet",
        "weight": "Weight",
        "wheelchair": "Wheelchair",
        "wine-glass": "Wine Glass",
        "wrench": "Wrench"
    },
    "Payments & Shopping": {
        "bell": "Bell",
        "far-bell": "Bell",
        "bookmark": "Bookmark",
        "far-bookmark": "Bookmark",
        "bullhorn": "Bullhorn",
        "camera": "Camera",
        "camera-retro": "Camera Retro",
        "cart-arrow-down": "Cart Arrow Down",
        "cart-plus": "Cart Plus",
        "certificate": "Certificate",
        "credit-card": "Credit Card",
        "far-credit-card": "Credit Card",
        "gem": "Gem",
        "far-gem": "Gem",
        "gift": "Gift",
        "handshake": "Handshake",
        "far-handshake": "Handshake",
        "heart": "Heart",
        "far-heart": "Heart",
        "key": "Key",
        "money-check": "Money Check",
        "money-check-alt": "Money Check Alt",
        "shopping-bag": "Shopping Bag",
        "shopping-basket": "Shopping Basket",
        "shopping-cart": "Shopping Cart",
        "star": "Star",
        "far-star": "Star",
        "tag": "Tag",
        "tags": "Tags",
        "thumbs-down": "Thumbs Down",
        "far-thumbs-down": "Thumbs Down",
        "thumbs-up": "Thumbs Up",
        "far-thumbs-up": "Thumbs Up",
        "trophy": "Trophy"
    },
    "Political": {
        "award": "Award",
        "balance-scale": "Balance Scale",
        "bullhorn": "Bullhorn",
        "check-double": "Check Double",
        "democrat": "Democrat",
        "donate": "Donate",
        "dove": "Dove",
        "fist-raised": "Fist Raised",
        "flag-usa": "Flag Usa",
        "handshake": "Handshake",
        "far-handshake": "Handshake",
        "person-booth": "Person Booth",
        "piggy-bank": "Piggy Bank",
        "republican": "Republican",
        "vote-yea": "Vote Yea"
    },
    "Religion": {
        "ankh": "Ankh",
        "atom": "Atom",
        "bible": "Bible",
        "church": "Church",
        "cross": "Cross",
        "dharmachakra": "Dharmachakra",
        "dove": "Dove",
        "gopuram": "Gopuram",
        "hamsa": "Hamsa",
        "hanukiah": "Hanukiah",
        "haykal": "Haykal",
        "jedi": "Jedi",
        "journal-whills": "Journal Whills",
        "kaaba": "Kaaba",
        "khanda": "Khanda",
        "menorah": "Menorah",
        "mosque": "Mosque",
        "om": "Om",
        "pastafarianism": "Pastafarianism",
        "peace": "Peace",
        "place-of-worship": "Place Of Worship",
        "pray": "Pray",
        "praying-hands": "Praying Hands",
        "quran": "Quran",
        "star-and-crescent": "Star And Crescent",
        "star-of-david": "Star Of David",
        "synagogue": "Synagogue",
        "torah": "Torah",
        "torii-gate": "Torii Gate",
        "vihara": "Vihara",
        "yin-yang": "Yin Yang"
    },
    "Shapes": {
        "bookmark": "Bookmark",
        "far-bookmark": "Bookmark",
        "calendar": "Calendar",
        "far-calendar": "Calendar",
        "certificate": "Certificate",
        "circle": "Circle",
        "far-circle": "Circle",
        "cloud": "Cloud",
        "comment": "Comment",
        "far-comment": "Comment",
        "file": "File",
        "far-file": "File",
        "folder": "Folder",
        "far-folder": "Folder",
        "heart": "Heart",
        "far-heart": "Heart",
        "heart-broken": "Heart Broken",
        "map-marker": "Map Marker",
        "play": "Play",
        "shapes": "Shapes",
        "square": "Square",
        "far-square": "Square",
        "star": "Star",
        "far-star": "Star"
    },
    "Spinners": {
        "asterisk": "Asterisk",
        "atom": "Atom",
        "certificate": "Certificate",
        "circle-notch": "Circle Notch",
        "cog": "Cog",
        "compact-disc": "Compact Disc",
        "compass": "Compass",
        "far-compass": "Compass",
        "crosshairs": "Crosshairs",
        "dharmachakra": "Dharmachakra",
        "haykal": "Haykal",
        "life-ring": "Life Ring",
        "far-life-ring": "Life Ring",
        "palette": "Palette",
        "ring": "Ring",
        "slash": "Slash",
        "snowflake": "Snowflake",
        "far-snowflake": "Snowflake",
        "spinner": "Spinner",
        "stroopwafel": "Stroopwafel",
        "sun": "Sun",
        "far-sun": "Sun",
        "sync": "Sync",
        "sync-alt": "Sync Alt",
        "yin-yang": "Yin Yang"
    },
    "Sports": {
        "baseball-ball": "Baseball Ball",
        "basketball-ball": "Basketball Ball",
        "bowling-ball": "Bowling Ball",
        "dumbbell": "Dumbbell",
        "football-ball": "Football Ball",
        "futbol": "Futbol",
        "far-futbol": "Futbol",
        "golf-ball": "Golf Ball",
        "hockey-puck": "Hockey Puck",
        "quidditch": "Quidditch",
        "skating": "Skating",
        "skiing": "Skiing",
        "skiing-nordic": "Skiing Nordic",
        "snowboarding": "Snowboarding",
        "table-tennis": "Table Tennis",
        "volleyball-ball": "Volleyball Ball"
    },
    "Status": {
        "ban": "Ban",
        "battery-empty": "Battery Empty",
        "battery-full": "Battery Full",
        "battery-half": "Battery Half",
        "battery-quarter": "Battery Quarter",
        "battery-three-quarters": "Battery Three Quarters",
        "bell": "Bell",
        "far-bell": "Bell",
        "bell-slash": "Bell Slash",
        "far-bell-slash": "Bell Slash",
        "calendar": "Calendar",
        "far-calendar": "Calendar",
        "calendar-alt": "Calendar Alt",
        "far-calendar-alt": "Calendar Alt",
        "calendar-check": "Calendar Check",
        "far-calendar-check": "Calendar Check",
        "calendar-day": "Calendar Day",
        "calendar-minus": "Calendar Minus",
        "far-calendar-minus": "Calendar Minus",
        "calendar-plus": "Calendar Plus",
        "far-calendar-plus": "Calendar Plus",
        "calendar-times": "Calendar Times",
        "far-calendar-times": "Calendar Times",
        "calendar-week": "Calendar Week",
        "cart-arrow-down": "Cart Arrow Down",
        "cart-plus": "Cart Plus",
        "comment": "Comment",
        "far-comment": "Comment",
        "comment-alt": "Comment Alt",
        "far-comment-alt": "Comment Alt",
        "comment-slash": "Comment Slash",
        "compass": "Compass",
        "far-compass": "Compass",
        "door-closed": "Door Closed",
        "door-open": "Door Open",
        "exclamation": "Exclamation",
        "exclamation-circle": "Exclamation Circle",
        "exclamation-triangle": "Exclamation Triangle",
        "eye": "Eye",
        "far-eye": "Eye",
        "eye-slash": "Eye Slash",
        "far-eye-slash": "Eye Slash",
        "file": "File",
        "far-file": "File",
        "file-alt": "File Alt",
        "far-file-alt": "File Alt",
        "folder": "Folder",
        "far-folder": "Folder",
        "folder-open": "Folder Open",
        "far-folder-open": "Folder Open",
        "gas-pump": "Gas Pump",
        "info": "Info",
        "info-circle": "Info Circle",
        "lightbulb": "Lightbulb",
        "far-lightbulb": "Lightbulb",
        "lock": "Lock",
        "lock-open": "Lock Open",
        "map-marker": "Map Marker",
        "map-marker-alt": "Map Marker Alt",
        "microphone": "Microphone",
        "microphone-alt": "Microphone Alt",
        "microphone-alt-slash": "Microphone Alt Slash",
        "microphone-slash": "Microphone Slash",
        "minus": "Minus",
        "minus-circle": "Minus Circle",
        "minus-square": "Minus Square",
        "far-minus-square": "Minus Square",
        "parking": "Parking",
        "phone": "Phone",
        "phone-slash": "Phone Slash",
        "plus": "Plus",
        "plus-circle": "Plus Circle",
        "plus-square": "Plus Square",
        "far-plus-square": "Plus Square",
        "print": "Print",
        "question": "Question",
        "question-circle": "Question Circle",
        "far-question-circle": "Question Circle",
        "shield-alt": "Shield Alt",
        "shopping-cart": "Shopping Cart",
        "sign-in-alt": "Sign In Alt",
        "sign-out-alt": "Sign Out Alt",
        "signal": "Signal",
        "smoking-ban": "Smoking Ban",
        "star": "Star",
        "far-star": "Star",
        "star-half": "Star Half",
        "far-star-half": "Star Half",
        "star-half-alt": "Star Half Alt",
        "stream": "Stream",
        "thermometer-empty": "Thermometer Empty",
        "thermometer-full": "Thermometer Full",
        "thermometer-half": "Thermometer Half",
        "thermometer-quarter": "Thermometer Quarter",
        "thermometer-three-quarters": "Thermometer Three Quarters",
        "thumbs-down": "Thumbs Down",
        "far-thumbs-down": "Thumbs Down",
        "thumbs-up": "Thumbs Up",
        "far-thumbs-up": "Thumbs Up",
        "tint": "Tint",
        "tint-slash": "Tint Slash",
        "toggle-off": "Toggle Off",
        "toggle-on": "Toggle On",
        "unlock": "Unlock",
        "unlock-alt": "Unlock Alt",
        "user": "User",
        "far-user": "User",
        "user-alt": "User Alt",
        "user-alt-slash": "User Alt Slash",
        "user-slash": "User Slash",
        "video": "Video",
        "video-slash": "Video Slash",
        "volume-down": "Volume Down",
        "volume-mute": "Volume Mute",
        "volume-off": "Volume Off",
        "volume-up": "Volume Up",
        "wifi": "Wifi"
    },
    "Tabletop Gaming": {
        "book-dead": "Book Dead",
        "dice-d20": "Dice D20",
        "dice-d6": "Dice D6",
        "dragon": "Dragon",
        "dungeon": "Dungeon",
        "fist-raised": "Fist Raised",
        "hat-wizard": "Hat Wizard",
        "ring": "Ring",
        "scroll": "Scroll",
        "skull-crossbones": "Skull Crossbones"
    },
    "Travel": {
        "archway": "Archway",
        "atlas": "Atlas",
        "bed": "Bed",
        "bus": "Bus",
        "bus-alt": "Bus Alt",
        "cocktail": "Cocktail",
        "concierge-bell": "Concierge Bell",
        "dumbbell": "Dumbbell",
        "glass-martini": "Glass Martini",
        "glass-martini-alt": "Glass Martini Alt",
        "globe-africa": "Globe Africa",
        "globe-americas": "Globe Americas",
        "globe-asia": "Globe Asia",
        "globe-europe": "Globe Europe",
        "hot-tub": "Hot Tub",
        "hotel": "Hotel",
        "luggage-cart": "Luggage Cart",
        "map": "Map",
        "far-map": "Map",
        "map-marked": "Map Marked",
        "map-marked-alt": "Map Marked Alt",
        "monument": "Monument",
        "passport": "Passport",
        "plane": "Plane",
        "plane-arrival": "Plane Arrival",
        "plane-departure": "Plane Departure",
        "shuttle-van": "Shuttle Van",
        "spa": "Spa",
        "suitcase": "Suitcase",
        "suitcase-rolling": "Suitcase Rolling",
        "swimmer": "Swimmer",
        "swimming-pool": "Swimming Pool",
        "taxi": "Taxi",
        "tram": "Tram",
        "umbrella-beach": "Umbrella Beach",
        "wine-glass": "Wine Glass",
        "wine-glass-alt": "Wine Glass Alt"
    },
    "Users & People": {
        "address-book": "Address Book",
        "far-address-book": "Address Book",
        "address-card": "Address Card",
        "far-address-card": "Address Card",
        "baby": "Baby",
        "bed": "Bed",
        "blind": "Blind",
        "chalkboard-teacher": "Chalkboard Teacher",
        "child": "Child",
        "female": "Female",
        "frown": "Frown",
        "far-frown": "Frown",
        "hiking": "Hiking",
        "id-badge": "Id Badge",
        "far-id-badge": "Id Badge",
        "id-card": "Id Card",
        "far-id-card": "Id Card",
        "id-card-alt": "Id Card Alt",
        "male": "Male",
        "meh": "Meh",
        "far-meh": "Meh",
        "people-carry": "People Carry",
        "person-booth": "Person Booth",
        "poo": "Poo",
        "portrait": "Portrait",
        "power-off": "Power Off",
        "pray": "Pray",
        "restroom": "Restroom",
        "running": "Running",
        "skating": "Skating",
        "skiing": "Skiing",
        "skiing-nordic": "Skiing Nordic",
        "smile": "Smile",
        "far-smile": "Smile",
        "snowboarding": "Snowboarding",
        "street-view": "Street View",
        "swimmer": "Swimmer",
        "user": "User",
        "far-user": "User",
        "user-alt": "User Alt",
        "user-alt-slash": "User Alt Slash",
        "user-astronaut": "User Astronaut",
        "user-check": "User Check",
        "user-circle": "User Circle",
        "far-user-circle": "User Circle",
        "user-clock": "User Clock",
        "user-cog": "User Cog",
        "user-edit": "User Edit",
        "user-friends": "User Friends",
        "user-graduate": "User Graduate",
        "user-injured": "User Injured",
        "user-lock": "User Lock",
        "user-md": "User Md",
        "user-minus": "User Minus",
        "user-ninja": "User Ninja",
        "user-nurse": "User Nurse",
        "user-plus": "User Plus",
        "user-secret": "User Secret",
        "user-shield": "User Shield",
        "user-slash": "User Slash",
        "user-tag": "User Tag",
        "user-tie": "User Tie",
        "user-times": "User Times",
        "users": "Users",
        "users-cog": "Users Cog",
        "walking": "Walking",
        "wheelchair": "Wheelchair"
    },
    "Vehicles": {
        "ambulance": "Ambulance",
        "baby-carriage": "Baby Carriage",
        "bicycle": "Bicycle",
        "bus": "Bus",
        "bus-alt": "Bus Alt",
        "car": "Car",
        "car-alt": "Car Alt",
        "car-crash": "Car Crash",
        "car-side": "Car Side",
        "fighter-jet": "Fighter Jet",
        "helicopter": "Helicopter",
        "horse": "Horse",
        "motorcycle": "Motorcycle",
        "paper-plane": "Paper Plane",
        "far-paper-plane": "Paper Plane",
        "plane": "Plane",
        "rocket": "Rocket",
        "ship": "Ship",
        "shopping-cart": "Shopping Cart",
        "shuttle-van": "Shuttle Van",
        "sleigh": "Sleigh",
        "snowplow": "Snowplow",
        "space-shuttle": "Space Shuttle",
        "subway": "Subway",
        "taxi": "Taxi",
        "tractor": "Tractor",
        "train": "Train",
        "tram": "Tram",
        "truck": "Truck",
        "truck-monster": "Truck Monster",
        "truck-pickup": "Truck Pickup",
        "wheelchair": "Wheelchair"
    },
    "Weather": {
        "bolt": "Bolt",
        "cloud": "Cloud",
        "cloud-meatball": "Cloud Meatball",
        "cloud-moon": "Cloud Moon",
        "cloud-moon-rain": "Cloud Moon Rain",
        "cloud-rain": "Cloud Rain",
        "cloud-showers-heavy": "Cloud Showers Heavy",
        "cloud-sun": "Cloud Sun",
        "cloud-sun-rain": "Cloud Sun Rain",
        "meteor": "Meteor",
        "moon": "Moon",
        "far-moon": "Moon",
        "poo-storm": "Poo Storm",
        "rainbow": "Rainbow",
        "smog": "Smog",
        "snowflake": "Snowflake",
        "far-snowflake": "Snowflake",
        "sun": "Sun",
        "far-sun": "Sun",
        "temperature-high": "Temperature High",
        "temperature-low": "Temperature Low",
        "umbrella": "Umbrella",
        "water": "Water",
        "wind": "Wind"
    },
    "Winter": {
        "glass-whiskey": "Glass Whiskey",
        "icicles": "Icicles",
        "igloo": "Igloo",
        "mitten": "Mitten",
        "skating": "Skating",
        "skiing": "Skiing",
        "skiing-nordic": "Skiing Nordic",
        "snowboarding": "Snowboarding",
        "snowplow": "Snowplow",
        "tram": "Tram"
    },
    "Writing": {
        "archive": "Archive",
        "blog": "Blog",
        "book": "Book",
        "bookmark": "Bookmark",
        "far-bookmark": "Bookmark",
        "edit": "Edit",
        "far-edit": "Edit",
        "envelope": "Envelope",
        "far-envelope": "Envelope",
        "envelope-open": "Envelope Open",
        "far-envelope-open": "Envelope Open",
        "eraser": "Eraser",
        "file": "File",
        "far-file": "File",
        "file-alt": "File Alt",
        "far-file-alt": "File Alt",
        "folder": "Folder",
        "far-folder": "Folder",
        "folder-open": "Folder Open",
        "far-folder-open": "Folder Open",
        "keyboard": "Keyboard",
        "far-keyboard": "Keyboard",
        "newspaper": "Newspaper",
        "far-newspaper": "Newspaper",
        "paper-plane": "Paper Plane",
        "far-paper-plane": "Paper Plane",
        "paperclip": "Paperclip",
        "paragraph": "Paragraph",
        "pen": "Pen",
        "pen-alt": "Pen Alt",
        "pen-square": "Pen Square",
        "pencil-alt": "Pencil Alt",
        "quote-left": "Quote Left",
        "quote-right": "Quote Right",
        "sticky-note": "Sticky Note",
        "far-sticky-note": "Sticky Note",
        "thumbtack": "Thumbtack"
    }
};