var ispConst = {
    TYPE_EVENT : 'event',
    TYPE_EVENT_THUMB : 'eventThumb',
    TYPE_COMMAND : 'command',
    TYPE_COMMAND_THUMB : 'commandThumb',
    TYPE_AGGREGATE : 'aggregate',
    TYPE_AGGREGATE_THUMB : 'aggregateThumb',
    TYPE_POLICY : 'policy',
    TYPE_POLICY_THUMB : 'policyThumb',
    TYPE_PROJECTION : 'projection',
    TYPE_PROJECTION_THUMB : 'projectionThumb',
    TYPE_DOCUMENT : 'document',
    TYPE_DOCUMENT_THUMB : 'documentThumb',
    TYPE_FEATURE : 'feature',
    TYPE_FEATURE_THUMB : 'featureThumb',
    TYPE_SWIMLANES_THUMB : 'swimlanesThumb',
    TYPE_BC : 'boundedContext',
    TYPE_BC_THUMB : 'boundedContextThumb',
    TYPE_ROLE : 'role',
    TYPE_ROLE_THUMB : 'roleThumb',
    TYPE_HOT_SPOT : 'hotSpot',
    TYPE_HOT_SPOT_THUMB : 'hotSpotThumb',
    TYPE_EXTERNAL_SYSTEM : 'externalSystem',
    TYPE_EXTERNAL_SYSTEM_THUMB : 'externalSystemThumb',
    TYPE_UI : 'ui',
    TYPE_UI_THUMB : 'uiThumb',
    TYPE_FREE_TEXT : 'freeText',
    TYPE_FREE_TEXT_THUMB : 'freeTextThumb',
    TYPE_TEXT_CARD : 'textCard',
    TYPE_TEXT_CARD_THUMB : 'textCardThumb',
    TYPE_IMAGE : 'image',
    TYPE_IMAGE_THUMB : 'imageThumb',
    TYPE_ICON : 'icon',
    TYPE_ICON_THUMB : 'iconThumb',
    TYPE_IFRAME : 'iframe',
    TYPE_IFRAME_THUMB : 'iframeThumb',

    TAGS_ATTR : 'tags',

    TAG_IMPORTANT : 'important',
    TAG_PLANNED : 'planned',
    TAG_READY : 'ready',
    TAG_DEPLOYED : 'deployed',
    TAG_CONNECTED : 'pb:connected',
    TAG_DISCONNECTED : 'pb:disconnected',
    /* TAG no longer in use, but kept for BC, replaced by TAG_EVENT_MODEL */
    TAG_SLICE : 'pb:slice',
    TAG_EVENT_MODEL: 'pb:eventmodel',
    TAG_DEFAULT_SLICE : 'pb:defaultslice',
    TAG_DEFAULT_EVENT_MODEL : 'pb:defaulteventmodel',
    TAG_LANE_HANDLE : 'pb:lanehandle',
    TAG_TIME_HANDLE : 'pb:timehandle',
    TAG_LANE_WATERMARK : 'pb:lanewatermark',
    TAG_SLICE_API_LABEL : 'pb:apilabel',
    TAG_ELEMENTS_TREE_HIDDEN : 'pb:ethidden',

    DEFAULT_DOC_NS : '/App',
    DEFAULT_SLICE_LANE_HEIGHT : 300,
    SLICE_LANE_EDGE_STYLE : 'edgeStyle=isometricEdgeStyle;html=1;startArrow=none;endArrow=none;strokeWidth=2;strokeColor=#bababa;',

    FILL_COLOR_TAG_IMPORTANT : '#FF9999',
    FILL_COLOR_TAG_PLANNED : '#FFE1AD',
    FILL_COLOR_TAG_READY : '#B9E0A5',
    FILL_COLOR_DEFAULT_FEATURE : '#E6E6E6',
    FILL_COLOR_DEFAULT_CONTEXT : '#A2A2A2',

    EVENT_COLOR: '#FF9F4B',
    COMMAND_COLOR: '#26C0E7',
    ROLE_COLOR: '#f7f727',
    AGGREGATE_COLOR: '#F5E339',
    DOCUMENT_COLOR: '#73dd8e',
    POLICY_COLOR: '#EABFF1',
    HOT_SPOT_COLOR: '#f31d30',
    EXTERNAL_SYSTEM_COLOR: '#ec98ac',
    UI_COLOR: '#000000',


    ZOOM_MODE_BC_ONLY : 'bcOnly',
    ZOOM_MODE_BC_AND_PROCESS : 'bcAndProcess',
    ZOOM_MODE_ALL_ELES : 'allEles',

    //Style
    THEME : 'material20',

    PROCESS_BORDER_COLOR : '#919191',

    STYLE_GRAPH_GRID_STYLE : 'gridStyle',
    STYLE_GRAPH_GRID_SIZE : 'gridSize',
    STYLE_GRAPH_GRID_STEPS : 'gridSteps',
    STYLE_GRAPH_GRID_MIN_GRID_SIZE : 'minGridSize',
    STYLE_GRAPH_GRID_COLOR : 'gridColor',
    STYLE_GRAPH_BG_COLOR : 'bgColor',

    GRID_STYLE_DOTTED : 'dotted',
    GRID_STYLE_LINED : 'lined',

    CMD_PICK_COLOR_CELL_BACKGROUND : 'cell.background',

    LANE_WATERMARK_DISTANCE : 2000,
};
